import logging


logger = logging.getLogger(__name__)


# Hardcoded list of suggestions (will be removed in the productionized code).
def job_suggestions():
    suggestions = [
        {
            "JOB TITLE": "Cultural Event Assistant",
            "DESCRIPTION": "Assist in organizing and executing cultural events, such as art exhibitions, concerts, "
                           "or theater performances. This role involves tasks like ticketing, coordinating "
                           "volunteers, and providing logistical support.",
            "LINK": "https://jobs.makesense.org/en/jobs/delta-france-association-stage-assistante-relations-institutionnelles-culture-HLD7D9ws3Sd0sQUlbqqQ?"
        },
        {
            "JOB TITLE": "Tour Guide",
            "DESCRIPTION": "Lead tours for tourists and visitors, providing information and insights about the "
                           "history, art, and culture of Paris. Requires strong communication skills and knowledge of"
                           " the city.",
            "LINK": "https://jobs.makesense.org/en/jobs/delta-france-association-stage-assistante-relations-institutionnelles-culture-HLD7D9ws3Sd0sQUlbqqQ?"
        },
    ]
    return suggestions


def get_job_suggestions(userid: str, job_preferences_nl: str):
    # TODO: get the data for this user (from the storage)
    # TODO: perform the job matching for real
    return {'content': job_suggestions(),
            'meta': {
                'reply_to': userid,
                'debug': "This data will be generated by LLM. For now, it's a stub."
            }}